### ISSUE TITLE
Deployed version is broken -- "Internal Server Error"

### ISSUE THREAD

**Issue by sjfink** [CognitiveBuild/Chatbot#2]
screenshot attached
<img width="1282" alt="screen shot 2017-04-17 at 11 10 09 am" src="https://cloud.githubusercontent.com/assets/1533170/25093059/8005af06-235e-11e7-861b-7606a2030976.png">

**Comment by mihui** [comment]
Hi  @sjfink thanks for reporting this issue, we will get back to you as soon as possible.

**Comment by sjfink** [comment]
I didn't deploy anything ... I simply clicked:

https://webchatbot.mybluemix.net/

**Comment by mihui** [comment]
Hey @sjfink thanks for the update. The issue has been resolved.
